package View;

import Model.Produto;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.awt.Font;
import java.awt.Color;
import javax.swing.table.JTableHeader;
import java.text.SimpleDateFormat;

public class GerenciaProduto extends javax.swing.JFrame {

    private Produto objproduto; // cria o vínculo com o objproduto

    public GerenciaProduto() {
        initComponents();
        this.objproduto = new Produto(); // carrega objproduto
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_alterar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_descricaoproduto = new javax.swing.JTextArea();
        b_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_relatorio = new javax.swing.JComboBox<>();
        c_nomeproduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c_tipoorg1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c_quantidadeestoque = new javax.swing.JTextField();
        c_botaorelatorio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        c_variavelrelatorio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c_datavalidade = new javax.swing.JTextField();
        b_cancelar = new javax.swing.JButton();
        c_preco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Gerenciamento de Produtos");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 225));

        b_alterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        c_descricaoproduto.setColumns(20);
        c_descricaoproduto.setLineWrap(true);
        c_descricaoproduto.setRows(5);
        c_descricaoproduto.setWrapStyleWord(true);
        jScrollPane2.setViewportView(c_descricaoproduto);

        b_apagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do produto:");

        c_relatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos vencidos", "Produtos prestes à vencer", "Produtos mais caros", "Produtos mais baratos", "Produtos com estoque baixo", "Produtos sem estoque" }));
        c_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_relatorioActionPerformed(evt);
            }
        });

        jLabel2.setText("Relatório de:");

        jLabel3.setText("Descrição");

        c_tipoorg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Preço (Mais Baratos)", "Preço (Mais Caros)", "Nome", "Quantidade", "Validade" }));
        c_tipoorg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_tipoorg1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade de estoque");

        jLabel6.setText("Organizar tabela por:");

        c_quantidadeestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_quantidadeestoqueActionPerformed(evt);
            }
        });

        c_botaorelatorio.setText("Fazer Relatório");
        c_botaorelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_botaorelatorioActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço");

        jTableProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableProdutos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableProdutos.setForeground(new java.awt.Color(33, 33, 33));
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID do Produto", "Nome do Produto", "Descrição", "Quantidade", "Preço", "Data de Cadastro", "Data de Validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableProdutos.setFillsViewportHeight(true);
        jTableProdutos.setGridColor(new java.awt.Color(221, 221, 221));
        jTableProdutos.setIntercellSpacing(new java.awt.Dimension(0, 1));
        jTableProdutos.setName(""); // NOI18N
        jTableProdutos.setRowHeight(25);
        jTableProdutos.setSelectionBackground(new java.awt.Color(33, 150, 243));
        jTableProdutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableProdutos.setShowGrid(true);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jLabel7.setText("Data de validade");

        jLabel8.setText("Variável relatório:");

        c_datavalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_datavalidadeActionPerformed(evt);
            }
        });

        b_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        c_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_precoActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoFINAL2.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(c_tipoorg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(c_datavalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(b_cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(b_alterar)
                                .addGap(18, 18, 18)
                                .addComponent(b_apagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c_variavelrelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(c_botaorelatorio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_tipoorg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_variavelrelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_botaorelatorio))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datavalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_cancelar)
                            .addComponent(b_alterar)
                            .addComponent(b_apagar)))
                    .addComponent(jLabel9))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

            try {
                // recebendo e validando dados da interface grafica.
                int id_produto = 0;
                String nome_produto = "";
                String descricao_produto = "";
                int quantidade_estoque = 0;
                double preco = 0.0;
                Date data_cadastro = null;
                Date data_validade;

            // Nome
            if (this.c_nomeproduto.getText().trim().length() < 2) {
                throw new Mensagens("O nome do produto deve conter ao menos 2 caracteres.");
            } else {
                nome_produto = this.c_nomeproduto.getText().trim();
            }

            // Descrição
            if (this.c_descricaoproduto.getText().trim().length() < 3) {
                throw new Mensagens("A descrição deve conter ao menos 3 caracteres.");
            } else {
                descricao_produto = this.c_descricaoproduto.getText().trim();
            }

            // Quantidade
            String qtxt = this.c_quantidadeestoque.getText().trim();
            if (qtxt.isEmpty()) {
                throw new Mensagens("A quantidade do produto deve ser informada.");
            } else {
                quantidade_estoque = Integer.parseInt(qtxt);
                if (quantidade_estoque < 0) {
                    throw new Mensagens("A quantidade do produto não pode ser negativa.");
                }
            }

            // Preço
            String ptxt = this.c_preco.getText().trim();
            if (ptxt.isEmpty()) {
                throw new Mensagens("O preço do produto deve ser informado e maior que zero.");
            } else {
                preco = Double.parseDouble(ptxt.replace(",", "."));
                if (preco <= 0) {
                    throw new Mensagens("O preço do produto deve ser maior que zero.");
                }
            }
            
            // Data de validade (formato esperado dd/MM/yyyy)
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            if (this.c_datavalidade.getText().trim().isEmpty()) {
                throw new Mensagens("Informe a data de validade no formato dd/MM/yyyy.");
            } else {
                try {
                    java.util.Date parsed = sdf.parse(this.c_datavalidade.getText().trim());
                    data_validade = new java.sql.Date(parsed.getTime());
                } catch (java.text.ParseException ex) {
                    throw new Mensagens("Data de validade inválida. Use o formato dd/MM/yyyy.");
                }
            }

                    // Verifica seleção na tabela
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um produto para alterar.");
            } else {
                // opcional: manter ID da linha selecionada como fonte de verdade
                id_produto = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

        // envia os dados para o Produto processar
        if (this.objproduto.UpdateProdutoBD(id_produto, nome_produto, descricao_produto, quantidade_estoque, preco, data_cadastro, data_validade)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datavalidade.setText("");
                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");

            }
        
        System.out.println(this.objproduto.ordenarPorID().toString());

    } catch (Mensagens erro) {
        JOptionPane.showMessageDialog(null, erro.getMessage());
    } catch (NumberFormatException erro2) {
        JOptionPane.showMessageDialog(null, "Informe um número válido.");
    } finally {
        carregaTabela(); // atualiza a tabela.
        }
    }//GEN-LAST:event_b_alterarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        if (this.jTableProdutos.getSelectedRow() != -1) {

            String nome_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 1).toString();
            String descricao_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 2).toString();
            String quantidade_estoque = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 3).toString();
            String preco = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 4).toString();
            String data_validade = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 6).toString();
            
            this.c_nomeproduto.setText(nome_produto);
            this.c_descricaoproduto.setText(descricao_produto);
            this.c_quantidadeestoque.setText(quantidade_estoque);
            this.c_preco.setText(preco);
            this.c_datavalidade.setText(data_validade);

        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {
            // validando dados da interface grafica.
            int id = 0;
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Produto ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Produto processar
                if (this.objproduto.DeleteProdutoBD(id)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datavalidade.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Produto apagado com sucesso!");

                }

            }

            System.out.println(this.objproduto.ordenarPorID().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void c_quantidadeestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_quantidadeestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_quantidadeestoqueActionPerformed

    private void c_datavalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_datavalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_datavalidadeActionPerformed

    private void c_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_precoActionPerformed

    private void c_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_relatorioActionPerformed
        if (c_relatorio.getSelectedIndex() == 1) {
            JOptionPane.showMessageDialog(null, "Insira quantos dias antes do produto vencer em 'Variavel Relatório'.");
        } else if (c_relatorio.getSelectedIndex() == 4) {
            JOptionPane.showMessageDialog(null, "Insira a quantidade máxima de estoque em 'Variavel Relatório'.");
        }
        this.c_variavelrelatorio.setText("");
    }//GEN-LAST:event_c_relatorioActionPerformed

    private void c_tipoorg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_tipoorg1ActionPerformed
        carregaTabela();
    }//GEN-LAST:event_c_tipoorg1ActionPerformed

    private void c_botaorelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_botaorelatorioActionPerformed
        fazerRelatorio();
    }//GEN-LAST:event_c_botaorelatorioActionPerformed

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ArrayList<Produto> minhalista = new ArrayList<>();

        switch ( c_tipoorg1.getSelectedIndex()) { // muda a organização com base na Combo Box
            case 0 -> minhalista = objproduto.ordenarPorID(); // "ID"
            case 1 -> minhalista = objproduto.ordenarPorPrecoASC(); // "Preco (Mais Baratos)"
            case 2 -> minhalista = objproduto.ordenarPorPrecoDESC(); // "Preco (Mais Caros)"
            case 3 -> minhalista = objproduto.ordenarPorNome(); // "Nome"
            case 4 -> minhalista = objproduto.ordenarPorQuantidade(); // "Quantidade"
            case 5 -> minhalista = objproduto.ordenarPorValidade(); // "Validade"
        }

        for (Produto p : minhalista) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); // Converter as datas para dd/mm/yyyy.
            String formattedDataCadastro = formatter.format(p.getData_cadastro());
            String formattedDataValidade = formatter.format(p.getData_validade());
            
            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                p.getPreco(),
                formattedDataCadastro,
                formattedDataValidade,
            });
        }
    }
    
    public void fazerRelatorio() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ArrayList<Produto> minhalista = new ArrayList<>();

        switch ( c_relatorio.getSelectedIndex()) { // muda a organização com base na Combo Box
            case 0: // "Produtos vencidos"
                minhalista = objproduto.relatorioProdutosVencidos();
            break;
            case 1: // "Produtos prestes à vender"
                if (this.c_variavelrelatorio.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira quantos dias antes do produto vencer em 'Variavel Relatório'.");
                } else {
                    minhalista = objproduto.relatorioProdutosPrestesAVencer(Integer.parseInt(c_variavelrelatorio.getText()));
                }
            break;
            case 2: // "Produtos mais caros"
                minhalista = objproduto.relatorioProdutosMaisCaros(); 
            break;
            case 3: // "Produtos mais baratos"
                minhalista = objproduto.relatorioProdutosMaisBaratos(); 
            break;    
            case 4: // "Produtos com estoque baixo"
                if (this.c_variavelrelatorio.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira a quantidade máxima de estoque em 'Variavel Relatório'.");
                } else {
                    minhalista = objproduto.relatorioEstoqueBaixo(Integer.parseInt(c_variavelrelatorio.getText()));
                }
            break;
            case 5: // "Produtos sem estoque"
                minhalista = objproduto.relatorioSemEstoque();
            break;
        }
        
    for (Produto p : minhalista) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); // Converter as datas para dd/mm/yyyy.
            String formattedDataCadastro = formatter.format(p.getData_cadastro());
            String formattedDataValidade = formatter.format(p.getData_validade());

            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                p.getPreco(),
                formattedDataCadastro,
                formattedDataValidade,
            });
        }
    }
        
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaProduto().setVisible(true);
            }
        });
        
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton c_botaorelatorio;
    private javax.swing.JTextField c_datavalidade;
    private javax.swing.JTextArea c_descricaoproduto;
    private javax.swing.JTextField c_nomeproduto;
    private javax.swing.JTextField c_preco;
    private javax.swing.JTextField c_quantidadeestoque;
    private javax.swing.JComboBox<String> c_relatorio;
    private javax.swing.JComboBox<String> c_tipoorg1;
    private javax.swing.JTextField c_variavelrelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}