package View;

import Model.Produto;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;

public class GerenciaProduto extends javax.swing.JFrame {

    private Produto objproduto; // cria o vinculo com o objproduto

    public GerenciaProduto() {
        initComponents();
        this.objproduto = new Produto(); // carrega objproduto
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_nomeproduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_idproduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_descricaoproduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_quantidadeestoque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_datacadastro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_datavalidade = new javax.swing.JTextField();
        c_preco = new javax.swing.JTextField();

        setTitle("Gerenciamento de Produtos");
        setResizable(false);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_produto", "nome_produto", "descricao_produto", "quantidade_estoque", "preco", "data_cadastro", "data_validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);
        if (jTableProdutos.getColumnModel().getColumnCount() > 0) {
            jTableProdutos.getColumnModel().getColumn(0).setMinWidth(30);
            jTableProdutos.getColumnModel().getColumn(1).setMinWidth(100);
            jTableProdutos.getColumnModel().getColumn(2).setMinWidth(30);
            jTableProdutos.getColumnModel().getColumn(3).setMinWidth(100);
            jTableProdutos.getColumnModel().getColumn(4).setMinWidth(50);
        }

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do produto:");

        jLabel2.setText("ID do Produto");

        c_idproduto.setEditable(false);
        c_idproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_idprodutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição do Produto");

        jLabel4.setText("Quantidade de estoque");

        c_quantidadeestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_quantidadeestoqueActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço");

        c_datacadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_datacadastroActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de cadastro");

        jLabel7.setText("Data de validade");

        c_datavalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_datavalidadeActionPerformed(evt);
            }
        });

        c_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_precoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(b_alterar)
                        .addGap(18, 18, 18)
                        .addComponent(b_apagar))
                    .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_idproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_descricaoproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_datavalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_datacadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_idproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_datacadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_descricaoproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_datavalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar)
                    .addComponent(b_alterar)
                    .addComponent(b_apagar))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

            try {
                // recebendo e validando dados da interface grafica.
                int id_produto = 0;
                String nome_produto = "";
                String descricao_produto = "";
                int quantidade_estoque = 0;
                double preco = 0.0;
                Date data_cadastro;
                Date data_validade;
            
            // ID
            if (this.c_idproduto.getText().trim().length() <= 0) {
                throw new Mensagens("O ID do produto deve ser número e maior que zero.");
            } else {
                id_produto = Integer.parseInt(this.c_idproduto.getText().trim());
                if (id_produto <= 0) {
                    throw new Mensagens("O ID do produto deve ser maior que zero.");
                }
            }

            // Nome
            if (this.c_nomeproduto.getText().trim().length() < 2) {
                throw new Mensagens("O nome do produto deve conter ao menos 2 caracteres.");
            } else {
                nome_produto = this.c_nomeproduto.getText().trim();
            }

            // Descrição
            if (this.c_descricaoproduto.getText().trim().length() < 10) {
                throw new Mensagens("A descrição deve conter ao menos 10 caracteres.");
            } else {
                descricao_produto = this.c_descricaoproduto.getText().trim();
            }

            // Quantidade
            if (this.c_quantidadeestoque.getText().trim().length() <= 0) {
                throw new Mensagens("A quantidade do produto deve ser um número e maior que zero.");
            } else {
                quantidade_estoque = Integer.parseInt(this.c_quantidadeestoque.getText().trim());
                if (quantidade_estoque <= 0) {
                    throw new Mensagens("A quantidade do produto deve ser maior que zero.");
                }
            }

            // Preço
            if (this.c_preco.getText().trim().length() <= 0) {
                throw new Mensagens("O preço do produto deve ser um número e maior que zero.");
            } else {
                preco = Double.parseDouble(this.c_preco.getText().trim().replace(",", "."));
                if (preco <= 0) {
                    throw new Mensagens("O preço do produto deve ser maior que zero.");
                }
            }
            
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            if (this.c_datacadastro.getText().trim().isEmpty()) {
                throw new Mensagens("Informe a data de cadastro no formato dd/MM/yyyy.");
            } else {
                data_cadastro = java.sql.Date.valueOf(this.c_datacadastro.getText().trim());
            }

            if (this.c_datavalidade.getText().trim().isEmpty()) {
                throw new Mensagens("Informe a data de validade no formato dd/MM/yyyy.");
            } else {
                data_validade = java.sql.Date.valueOf(this.c_datavalidade.getText().trim());
            }

                    // Verifica seleção na tabela
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um produto para alterar.");
            } else {
                // opcional: manter ID da linha selecionada como fonte de verdade
                id_produto = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

        // envia os dados para o Produto processar
        if (this.objproduto.UpdateProdutoBD(id_produto, nome_produto, descricao_produto, quantidade_estoque, preco, data_cadastro, data_validade)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_idproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datacadastro.setText("");
                this.c_datavalidade.setText("");
                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");

            }
        
        System.out.println(this.objproduto.getMinhaLista().toString());

    } catch (Mensagens erro) {
        JOptionPane.showMessageDialog(null, erro.getMessage());
    } catch (NumberFormatException erro2) {
        JOptionPane.showMessageDialog(null, "Informe um número válido.");
    } finally {
        carregaTabela(); // atualiza a tabela.
        }
    }//GEN-LAST:event_b_alterarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        if (this.jTableProdutos.getSelectedRow() != -1) {

            String nome_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 1).toString();
            String id_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString();
            String descricao_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 2).toString();
            String quantidade_estoque = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 3).toString();
            String preco = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 4).toString();
            String data_cadastro = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 5).toString();
            String data_validade = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 6).toString();

            this.c_nomeproduto.setText(nome_produto);
            this.c_idproduto.setText(id_produto);
            this.c_descricaoproduto.setText(descricao_produto);
            this.c_quantidadeestoque.setText(quantidade_estoque);
            this.c_preco.setText(preco);
            this.c_datacadastro.setText(data_cadastro);
            this.c_datavalidade.setText(data_validade);

        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {
            // validando dados da interface grafica.
            int id = 0;
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Produto ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Produto processar
                if (this.objproduto.DeleteProdutoBD(id)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_idproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datacadastro.setText("");
                this.c_datavalidade.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Produto apagado com sucesso!");

                }

            }

            System.out.println(this.objproduto.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void c_idprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_idprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_idprodutoActionPerformed

    private void c_quantidadeestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_quantidadeestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_quantidadeestoqueActionPerformed

    private void c_datacadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_datacadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_datacadastroActionPerformed

    private void c_datavalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_datavalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_datavalidadeActionPerformed

    private void c_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_precoActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("unchecked")
    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ArrayList<Produto> minhalista = new ArrayList<>();
        minhalista = objproduto.getMinhaLista();

        for (Produto p : minhalista) {
            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                p.getPreco(),
                p.getData_cadastro(),
                p.getData_validade(),
            });
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaProduto().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JTextField c_datacadastro;
    private javax.swing.JTextField c_datavalidade;
    private javax.swing.JTextField c_descricaoproduto;
    private javax.swing.JTextField c_idproduto;
    private javax.swing.JTextField c_nomeproduto;
    private javax.swing.JTextField c_preco;
    private javax.swing.JTextField c_quantidadeestoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
