package View;

import Model.Produto;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.awt.Font;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.table.JTableHeader;
import javax.swing.border.Border;
import DAO.ProdutoDAO;
import java.text.SimpleDateFormat;

public class GerenciaProduto extends javax.swing.JFrame {

    private Produto objproduto; // cria o vinculo com o objproduto

    public GerenciaProduto() {
        initComponents();
        this.objproduto = new Produto(); // carrega objproduto
        this.carregaTabela();
        
    // Cabeçalho da tabela
    JTableHeader header = jTableProdutos.getTableHeader();
    header.setFont(new Font("Segoe UI", Font.BOLD, 14));
    header.setBackground(new Color(46, 125, 50));
    header.setForeground(Color.WHITE);

    // Borda arredondada no JScrollPane
    jScrollPane1.setBorder(new javax.swing.border.LineBorder(new Color(221, 221, 221), 1, true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_nomeproduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_quantidadeestoque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c_datavalidade = new javax.swing.JTextField();
        c_preco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        c_descricaoproduto = new javax.swing.JTextArea();
        c_tipoorg = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Gerenciamento de Produtos");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jTableProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableProdutos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableProdutos.setForeground(new java.awt.Color(33, 33, 33));
        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID do Produto", "Nome do Produto", "Descrição", "Quantidade", "Preço", "Data de Cadastro", "Data de Validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableProdutos.setFillsViewportHeight(true);
        jTableProdutos.setGridColor(new java.awt.Color(221, 221, 221));
        jTableProdutos.setIntercellSpacing(new java.awt.Dimension(0, 1));
        jTableProdutos.setName(""); // NOI18N
        jTableProdutos.setRowHeight(25);
        jTableProdutos.setSelectionBackground(new java.awt.Color(33, 150, 243));
        jTableProdutos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableProdutos.setShowGrid(true);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do produto:");

        jLabel3.setText("Descrição");

        jLabel4.setText("Quantidade de estoque");

        c_quantidadeestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_quantidadeestoqueActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço");

        jLabel7.setText("Data de validade");

        c_datavalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_datavalidadeActionPerformed(evt);
            }
        });

        c_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_precoActionPerformed(evt);
            }
        });

        c_descricaoproduto.setColumns(20);
        c_descricaoproduto.setLineWrap(true);
        c_descricaoproduto.setRows(5);
        c_descricaoproduto.setWrapStyleWord(true);
        jScrollPane2.setViewportView(c_descricaoproduto);

        c_tipoorg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Preço (Mais Baratos)", "Preço (Mais Caros)", "Nome", "Quantidade", "Validade" }));
        c_tipoorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_tipoorgActionPerformed(evt);
            }
        });

        jLabel2.setText("Organizar tabela por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addComponent(b_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(b_alterar)
                        .addGap(18, 18, 18)
                        .addComponent(b_apagar)
                        .addGap(487, 487, 487))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(c_datavalidade, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_preco))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_tipoorg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_tipoorg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_quantidadeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_datavalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar)
                    .addComponent(b_alterar)
                    .addComponent(b_apagar))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

            try {
                // recebendo e validando dados da interface grafica.
                int id_produto = 0;
                String nome_produto = "";
                String descricao_produto = "";
                int quantidade_estoque = 0;
                double preco = 0.0;
                Date data_cadastro = null;
                Date data_validade;

            // Nome
            if (this.c_nomeproduto.getText().trim().length() < 2) {
                throw new Mensagens("O nome do produto deve conter ao menos 2 caracteres.");
            } else {
                nome_produto = this.c_nomeproduto.getText().trim();
            }

            // Descrição
            if (this.c_descricaoproduto.getText().trim().length() < 3) {
                throw new Mensagens("A descrição deve conter ao menos 3 caracteres.");
            } else {
                descricao_produto = this.c_descricaoproduto.getText().trim();
            }

            // Quantidade
            String qtxt = this.c_quantidadeestoque.getText().trim();
            if (qtxt.isEmpty()) {
                throw new Mensagens("A quantidade do produto deve ser informada e maior que zero.");
            } else {
                quantidade_estoque = Integer.parseInt(qtxt);
                if (quantidade_estoque <= 0) {
                    throw new Mensagens("A quantidade do produto deve ser maior que zero.");
                }
            }

            // Preço
            String ptxt = this.c_preco.getText().trim();
            if (ptxt.isEmpty()) {
                throw new Mensagens("O preço do produto deve ser informado e maior que zero.");
            } else {
                preco = Double.parseDouble(ptxt.replace(",", "."));
                if (preco <= 0) {
                    throw new Mensagens("O preço do produto deve ser maior que zero.");
                }
            }
            
            // Data de validade (formato esperado dd/MM/yyyy)
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            if (this.c_datavalidade.getText().trim().isEmpty()) {
                throw new Mensagens("Informe a data de validade no formato dd/MM/yyyy.");
            } else {
                try {
                    java.util.Date parsed = sdf.parse(this.c_datavalidade.getText().trim());
                    data_validade = new java.sql.Date(parsed.getTime());
                } catch (java.text.ParseException ex) {
                    throw new Mensagens("Data de validade inválida. Use o formato dd/MM/yyyy.");
                }
            }

                    // Verifica seleção na tabela
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um produto para alterar.");
            } else {
                // opcional: manter ID da linha selecionada como fonte de verdade
                id_produto = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

        // envia os dados para o Produto processar
        if (this.objproduto.UpdateProdutoBD(id_produto, nome_produto, descricao_produto, quantidade_estoque, preco, data_cadastro, data_validade)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datavalidade.setText("");
                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");

            }
        
        System.out.println(this.objproduto.ordenarPorID().toString());

    } catch (Mensagens erro) {
        JOptionPane.showMessageDialog(null, erro.getMessage());
    } catch (NumberFormatException erro2) {
        JOptionPane.showMessageDialog(null, "Informe um número válido.");
    } finally {
        carregaTabela(); // atualiza a tabela.
        }
    }//GEN-LAST:event_b_alterarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        if (this.jTableProdutos.getSelectedRow() != -1) {

            String nome_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 1).toString();
            String descricao_produto = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 2).toString();
            String quantidade_estoque = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 3).toString();
            String preco = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 4).toString();
            String data_validadeString = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 6).toString();

            // converter a data de formato SQL (2025-02-25) para formato dd/mm/yyyy (25/02/2025)
            Date data_validade = Date.valueOf(data_validadeString);
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = formatter.format(data_validade);
            
            this.c_nomeproduto.setText(nome_produto);
            this.c_descricaoproduto.setText(descricao_produto);
            this.c_quantidadeestoque.setText(quantidade_estoque);
            this.c_preco.setText(preco);
            this.c_datavalidade.setText(formattedDate);

        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {
            // validando dados da interface grafica.
            int id = 0;
            if (this.jTableProdutos.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Produto ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Produto processar
                if (this.objproduto.DeleteProdutoBD(id)) {

                // limpa os campos
                this.c_nomeproduto.setText("");
                this.c_descricaoproduto.setText("");
                this.c_quantidadeestoque.setText("");
                this.c_preco.setText("");
                this.c_datavalidade.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Produto apagado com sucesso!");

                }

            }

            System.out.println(this.objproduto.ordenarPorID().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void c_quantidadeestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_quantidadeestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_quantidadeestoqueActionPerformed

    private void c_datavalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_datavalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_datavalidadeActionPerformed

    private void c_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_precoActionPerformed

    private void c_tipoorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_tipoorgActionPerformed
        carregaTabela();
    }//GEN-LAST:event_c_tipoorgActionPerformed

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ArrayList<Produto> minhalista = new ArrayList<>();

        switch ( c_tipoorg.getSelectedIndex()) { // muda a organização com base na Combo Box
            case 0 -> minhalista = objproduto.ordenarPorID(); // "ID"
            case 1 -> minhalista = objproduto.ordenarPorPrecoASC(); // "Preco (Mais Baratos)"
            case 2 -> minhalista = objproduto.ordenarPorPrecoDESC(); // "Preco (Mais Caros)"
            case 3 -> minhalista = objproduto.ordenarPorNome(); // "Nome"
            case 4 -> minhalista = objproduto.ordenarPorQuantidade(); // "Quantidade"
            case 5 -> minhalista = objproduto.ordenarPorValidade(); // "Validade"
        }

        for (Produto p : minhalista) {
            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                p.getPreco(),
                p.getData_cadastro(),
                p.getData_validade(),
            });
        }
    }



    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaProduto().setVisible(true);
            }
        });
        
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JTextField c_datavalidade;
    private javax.swing.JTextArea c_descricaoproduto;
    private javax.swing.JTextField c_nomeproduto;
    private javax.swing.JTextField c_preco;
    private javax.swing.JTextField c_quantidadeestoque;
    private javax.swing.JComboBox<String> c_tipoorg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}